version: '3.8'

services:
  postgres:
    image: postgres:16.3
    container_name: postgres-db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: lojavirtual
    ports:
      - "5432:5432"
    networks:
      - banco-postegres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80"
    networks:
      - banco-postegres

networks:
  banco-postegres:
    driver: bridge

volumes:
  postgres_data:
